// AUTO-GENERATED by scripts/gen-registry.ts — do not edit by hand.
import type { GameModule } from './core/module';

export { ENGINE_SLUGS, TIER1_SLUGS } from './slugs.generated';

/** Lazy loaders so each game ships in its own chunk (client code only). */
export const gameModuleLoaders: Record<string, () => Promise<GameModule>> = {
  'andar-bahar': () => import('./andar-bahar').then((m) => m.default as unknown as GameModule),
  'baccarat': () => import('./baccarat').then((m) => m.default as unknown as GameModule),
  'blackjack': () => import('./blackjack').then((m) => m.default as unknown as GameModule),
  'crazy-eights': () => import('./crazy-eights').then((m) => m.default as unknown as GameModule),
  'go-fish': () => import('./go-fish').then((m) => m.default as unknown as GameModule),
  'hearts': () => import('./hearts').then((m) => m.default as unknown as GameModule),
  'indian-rummy': () => import('./indian-rummy').then((m) => m.default as unknown as GameModule),
  'klondike': () => import('./klondike').then((m) => m.default as unknown as GameModule),
  'spades': () => import('./spades').then((m) => m.default as unknown as GameModule),
  'teen-patti': () => import('./teen-patti').then((m) => m.default as unknown as GameModule),
  'texas-holdem': () => import('./texas-holdem').then((m) => m.default as unknown as GameModule),
  'war': () => import('./war').then((m) => m.default as unknown as GameModule),
};
