// AUTO-GENERATED by scripts/gen-registry.ts — do not edit by hand.
// Data only: safe to import from server components (see the note at the top of the generator).

/** Slugs that have a full engine + board (Tier 1). */
export const TIER1_SLUGS: readonly string[] = ['andar-bahar', 'baccarat', 'blackjack', 'crazy-eights', 'go-fish', 'hearts', 'indian-rummy', 'klondike', 'spades', 'teen-patti', 'texas-holdem', 'war'];

/** Slugs with a rules engine (src/games/<slug>/engine.ts), wired up or not. */
export const ENGINE_SLUGS: readonly string[] = ['andar-bahar', 'baccarat', 'blackjack', 'crazy-eights', 'go-fish', 'hearts', 'indian-rummy', 'klondike', 'spades', 'teen-patti', 'texas-holdem', 'war'];
