/**
 * Generates the two registries so that adding a game never requires editing a
 * shared file:
 *   content/games/index.ts           ← every content/games/<slug>.ts
 *   src/games/registry.generated.ts  ← every src/games/<slug>/index.ts (Tier 1 modules)
 * Run with `npm run gen` (also runs automatically before dev/build/test/lint/typecheck).
 */
import { readdirSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const contentDir = path.join(root, 'content/games');
const gamesDir = path.join(root, 'src/games');

const toIdent = (slug: string) => slug.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

const contentSlugs = readdirSync(contentDir)
  .filter((f) => f.endsWith('.ts') && f !== 'index.ts' && !f.endsWith('.test.ts'))
  .map((f) => f.replace(/\.ts$/, ''))
  .sort();

const moduleSlugs = readdirSync(gamesDir, { withFileTypes: true })
  .filter((d) => d.isDirectory() && d.name !== 'core')
  .filter((d) => existsSync(path.join(gamesDir, d.name, 'index.ts')))
  .map((d) => d.name)
  .sort();

const header = '// AUTO-GENERATED by scripts/gen-registry.ts — do not edit by hand.\n';

const contentFile =
  header +
  "import type { GameContentInput } from '@/lib/content/schema';\n" +
  contentSlugs.map((s) => `import ${toIdent(s)} from './${s}';`).join('\n') +
  '\n\n/** Raw (unvalidated) content keyed by file slug. */\n' +
  'export const rawGameContent: Record<string, GameContentInput> = {\n' +
  contentSlugs.map((s) => `  '${s}': ${toIdent(s)},`).join('\n') +
  '\n};\n';

const registryFile =
  header +
  "import type { GameModule } from './core/module';\n\n" +
  '/** Slugs that have a full engine + board (Tier 1). */\n' +
  `export const TIER1_SLUGS: readonly string[] = [${moduleSlugs.map((s) => `'${s}'`).join(', ')}];\n\n` +
  '/** Lazy loaders so each game ships in its own chunk. */\n' +
  'export const gameModuleLoaders: Record<string, () => Promise<GameModule>> = {\n' +
  moduleSlugs
    .map(
      (s) =>
        `  '${s}': () => import('./${s}').then((m) => m.default as unknown as GameModule),`,
    )
    .join('\n') +
  '\n};\n';

function writeIfChanged(file: string, contents: string) {
  if (existsSync(file) && readFileSync(file, 'utf8') === contents) return false;
  writeFileSync(file, contents);
  return true;
}

const a = writeIfChanged(path.join(contentDir, 'index.ts'), contentFile);
const b = writeIfChanged(path.join(gamesDir, 'registry.generated.ts'), registryFile);
console.info(
  `gen-registry: ${contentSlugs.length} content files, ${moduleSlugs.length} game modules` +
    (a || b ? ' (updated)' : ' (unchanged)'),
);
