// AUTO-GENERATED by scripts/gen-registry.ts — do not edit by hand.
import type { GameContentInput } from '@/lib/content/schema';
import andarBahar from './andar-bahar';
import baccarat from './baccarat';
import belote from './belote';
import bigTwo from './big-two';
import blackjack from './blackjack';
import bridge from './bridge';
import briscola from './briscola';
import canasta from './canasta';
import cheat from './cheat';
import crazyEights from './crazy-eights';
import cribbage from './cribbage';
import durak from './durak';
import euchre from './euchre';
import freecell from './freecell';
import ginRummy from './gin-rummy';
import goFish from './go-fish';
import hearts from './hearts';
import indianRummy from './indian-rummy';
import klondike from './klondike';
import mendikot from './mendikot';
import oldMaid from './old-maid';
import president from './president';
import scopa from './scopa';
import skat from './skat';
import spades from './spades';
import spiderSolitaire from './spider-solitaire';
import teenPatti from './teen-patti';
import texasHoldem from './texas-holdem';
import tienLen from './tien-len';
import twentyNine from './twenty-nine';
import war from './war';

/** Raw (unvalidated) content keyed by file slug. */
export const rawGameContent: Record<string, GameContentInput> = {
  'andar-bahar': andarBahar,
  'baccarat': baccarat,
  'belote': belote,
  'big-two': bigTwo,
  'blackjack': blackjack,
  'bridge': bridge,
  'briscola': briscola,
  'canasta': canasta,
  'cheat': cheat,
  'crazy-eights': crazyEights,
  'cribbage': cribbage,
  'durak': durak,
  'euchre': euchre,
  'freecell': freecell,
  'gin-rummy': ginRummy,
  'go-fish': goFish,
  'hearts': hearts,
  'indian-rummy': indianRummy,
  'klondike': klondike,
  'mendikot': mendikot,
  'old-maid': oldMaid,
  'president': president,
  'scopa': scopa,
  'skat': skat,
  'spades': spades,
  'spider-solitaire': spiderSolitaire,
  'teen-patti': teenPatti,
  'texas-holdem': texasHoldem,
  'tien-len': tienLen,
  'twenty-nine': twentyNine,
  'war': war,
};
