// AUTO-GENERATED by scripts/gen-registry.ts — do not edit by hand.
import type { GameContentInput } from '@/lib/content/schema';


/** Raw (unvalidated) content keyed by file slug. */
export const rawGameContent: Record<string, GameContentInput> = {

};
